name = "VB.NET"
code_fence_block_name = "vb"
grammar = "vbnet"
path_suffixes = ["vb"]
line_comments = ["' "]
tab_size = 4
autoclose_before = ";:.,=}])>"

brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = false, not_in = ["comment", "string"] },
]
